// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-zFQz0W731Lr3SVD52yjwKtO16mUydE4',
    appId: '1:531107985123:web:0b5b88dc5419fa0998b7d6',
    messagingSenderId: '531107985123',
    projectId: 'misexams-33e44',
    authDomain: 'misexams-33e44.firebaseapp.com',
    storageBucket: 'misexams-33e44.appspot.com',
    measurementId: 'G-N6TZF13L7F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcZj7dbunReBUcPVNJ2wimgEg20T5fqVo',
    appId: '1:531107985123:android:3211aadd02cfa5dc98b7d6',
    messagingSenderId: '531107985123',
    projectId: 'misexams-33e44',
    storageBucket: 'misexams-33e44.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnz1vlQFNsvaoZXjph0G3YXWj8yuL1138',
    appId: '1:531107985123:ios:d38cb0ae8f0fe6fc98b7d6',
    messagingSenderId: '531107985123',
    projectId: 'misexams-33e44',
    storageBucket: 'misexams-33e44.appspot.com',
    iosBundleId: 'com.example.lab5201177',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnz1vlQFNsvaoZXjph0G3YXWj8yuL1138',
    appId: '1:531107985123:ios:fdaf8b84f7d1b7f298b7d6',
    messagingSenderId: '531107985123',
    projectId: 'misexams-33e44',
    storageBucket: 'misexams-33e44.appspot.com',
    iosBundleId: 'com.example.lab5201177.RunnerTests',
  );
}
